### ISSUE TITLE
[Intergreatly] - webapp to display logged in user info

### ISSUE THREAD

**Issue by VinayBhalerao** [RedHatWorkshops/dayinthelife-integration#117]
With current tutorial app https://tutorial-web-app-webapp.dil.opentry.me/ when a user logins , it wil be nice to show the user the `username` instead of `developer` per below screenshot

**Need?**
Few users will tend to hands-on both labs, citizen integrator and developer, once they login it will be tricky to track down which user logged in.

**Screenshot**
![red_hat_solution_explorer](https://user-images.githubusercontent.com/7827135/47519394-617fb280-d842-11e8-8f47-989ef0566cc8.png)

**Comment by sigreen** [comment]
This problem was resolved on the new cluster (dil1.opentry.me)

**Comment by VinayBhalerao** [comment]
Looks like the issue is back. Below is the screenshot from the dil cluster

![red_hat_solution_explorer](https://user-images.githubusercontent.com/7827135/48098754-72311080-e1d2-11e8-8334-435fe323fa5c.png)
